### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Plazmius** [Mrackushka/KPI-OOP-LR1#1]
1. Ми можемо дуже довго дискутувати про те як принципи ООП однакові чи не однакові залежно від інструмента, і як інструмент впливає на знання. Але ми цього робити не будемо. Я дозволяю вам здавати лаби на пайтоні, якщо хочете, але теорію вам доведеться здавати для шарпів. 

2. https://github.com/Mrackushka/KPI-OOP-LR1/blob/5cd561ece4cfdb5d93df850bd63d3439577f2d11/LR-1.py#L36 - не можна опиратись на останню гру в списку. Зробіть гру результат якої розраховується або вхідним параметром, або перенесіть код виклику відповідних методів в окрему функцію\метод

**Comment by Mrackushka1** [comment]
1. Дуже дякую Вам за таку відповідь =)
2. Переписав досить значну частину Python програми для поліпшення якості коду. Відтепер доступ до поточної гри здійснюється не за останнім елементом списку ігор об'єкта класу `GameAccount`, а за допомогою додаткового атрибута `current_game` кожного такого об'єкта. Внаслідок створення такого атрибута необхідність зберігати у кожному екземплярі класу `Game` статус гри зникла, тож відповідний атрибут `Game.ended` був видалений.

**Comment by Plazmius** [comment]
Зараховано, 10
